import type { Question } from "./IQuestion";

export const unit5a: Question[] = [
  { word: "approach", type: "n", definition: "method, procedure, strategy.", example: "He has a relaxed approach to life." },
  { word: "aside from", type: "prep", definition: "except for one thing, sth. is true; apart from.", example: "Aside from hanging about in the street, there's nothing for kids to do here." },
  { word: "assess", type: "v", definition: "to evaluate, to judge, to analyze.", example: "Exams are not the only means of assessing a student's ability." },
  { word: "astonished", type: "adj", definition: "very surprised.", example: "I was astonished. I really wasn't expecting it." },
  { word: "avalanche", type: "n", definition: "a large amount of snow and ice that suddenly falls down a mountain.", example: "According to rescue workers, it will take several hours to dig people out of the avalanche of snow." },
  { word: "be (feel) down", type: "exp", definition: "to be sad or depressed.", example: "He's been feeling really down since his wife went away." },
  { word: "be scared stiff", type: "exp", definition: "to be terrified.", example: "I was scared stiff when I heard someone in our kitchen in the middle of the night." },
  { word: "be sick and tired of", type: "exp", definition: "to be fed up or irritated.", example: "I'm sick and tired of hearing your complaints about your job." },
  { word: "be worn out", type: "exp", definition: "to be exhausted.", example: "I'm absolutely worn out. I want to relax and put my feet up." },
  { word: "bewildered", type: "adj", definition: "extremely confused.", example: "I'm just completely bewildered by so many facts and figures." },
  { word: "bite", type: "n", definition: "an act of biting (To bite: To use your teeth to cut into or through sth).", example: "You eat a sandwich one bite at a time." },
  { word: "breath", type: "n", definition: "the air that goes in and out of your body through your nose or mouth.", example: "I could smell whisky on his breath." },
  { word: "breathe", type: "v", definition: "to take air into your lungs through your nose or mouth and let it out again.", example: "The instructor told us to breathe in deeply and then breathe out slowly." },
  { word: "bury", type: "v", definition: "to hide sth in the ground.", example: "If an avalanche strikes, skiers can be buried alive by snow." },
  { word: "cadet", type: "n", definition: "a young person who is training to become an officer in the police or armed forces.", example: "In Air force survival school they try to teach new cadets how to react in case of a life or death crisis or emergency." },
  { word: "challenge", type: "n", definition: "a new or difficult thing that tests your abilities.", example: "I was bored with my job and felt I needed a new challenge." },
  { word: "complain", type: "v", definition: "to say that you are annoyed, unhappy or not satisfied about something or somebody.", example: "Marcus was complaining about everything." },
  { word: "confront", type: "v", definition: "to deal with a problem or difficult situation.", example: "We need to confront these problems before it's too late." },
  { word: "coolly", type: "adv", definition: "in a way that is not friendly, interested or enthusiastic; in a calm way.", example: "Everyone must think this situation through calmly and coolly." },
  { word: "coverage", type: "n", definition: "the amount or way that something covers an area.", example: "What would you do if you were hiking alone in the mountains and you got completely lost (without phone coverage)?" },
  { word: "deal with", type: "v", definition: "to solve a problem, perform a task, etc.", example: "Survival means dealing with a huge life-or-death problem, one that you may not be able to solve quickly or all at once." },
  { word: "delighted", type: "adj", definition: "incredibly happy.", example: "Yes, we'd be delighted to." },
  { word: "despair", type: "v", definition: "to feel that a situation is so bad that nothing you can do will change it.", example: "Knowing the right thing to do in a crisis is also vital apart from not despairing." },
  { word: "desperate", type: "adj", definition: "with little hope, and ready to do anything to improve the situation.", example: "I was just robbed! Please come quickly. I'm desperate." },
  { word: "devastated", type: "adj", definition: "extremely upset.", example: "They were devastated." },
  { word: "disappointed", type: "adj", definition: "upset because something you hoped for has not happened or been as good, successful, etc. as you expected.", example: "To be honest, I was a little disappointed." },
  { word: "eventually", type: "adv", definition: "at the end of a period of time or a series of events.", example: "Eventually they decided to abandon the search." },
  { word: "face", type: "v", definition: "to deal with a difficult situation.", example: "Emergency services are facing additional problems this winter." },
  { word: "fed up", type: "adj", definition: "bored or frustrated and unhappy.", example: "I'm really fed up with my job." },
  { word: "freeze", type: "v", definition: "to stop moving suddenly because of fear, etc.", example: "I'd freeze and wouldn't be able to do anything." },
  { word: "get out", type: "v", definition: "to escape from a place.", example: "He was determined to get out of prison." },
  { word: "goal", type: "n", definition: "objective.", example: "One goal at a time, and one decision at a time." },
  { word: "grateful", type: "adj", definition: "thankful.", example: "She was grateful to them for letting her stay." },
  { word: "hike", type: "v", definition: "to go for a long walk in the country.", example: "We're going to hike to the top of that hill." },
  { word: "homesick", type: "adj", definition: "sad because you miss your family and home.", example: "Most people get homesick the first time they leave home." },
  { word: "horrified", type: "adj", definition: "extremely shocked or disgusted.", example: "I was absolutely horrified. It was such an awful accident." },
  { word: "injured", type: "adj", definition: "physically hurt.", example: "The car accident left him seriously injured." },
  { word: "insolvable", type: "adj", definition: "admitting no solution.", example: "No problem is insolvable if people are willing to consult with others." },
  { word: "instead of", type: "adv", definition: "in the place of sb/sth; by contrast.", example: "Now I can walk to work instead of going by car." },
  { word: "intruder", type: "n", definition: "a person who enters a building or an area illegally.", example: "What would you do if you thought you could hear an intruder in your home?" },
  { word: "jump for joy", type: "exp", definition: "to be extremely happy.", example: "He finally passed his driver's test. He's jumping for joy!" },
  { word: "lock", type: "v", definition: "to put sth in a safe place and lock it.", example: "I'd lock myself in a room and call the police." },
  { word: "manageable", type: "adj", definition: "able to be dealt with or controlled easily.", example: "Divide the challenges into small, manageable tasks." },
  { word: "not believe one's eyes", type: "exp", definition: "to be astonished.", example: "When I saw her, I couldn't believe my eyes." },
  { word: "overcome", type: "v", definition: "to succeed in dealing with or controlling a problem.", example: "He finally managed to overcome his fear of flying." },
  { word: "oversleep", type: "v", definition: "to sleep longer than you intended.", example: "Why are you so late? Did you oversleep again?" },
  { word: "overwhelmed", type: "adj", definition: "unable to react because the emotion is too strong.", example: "I'm completely overwhelmed - I don't know what to say!" },
  { word: "panic", type: "v", definition: "to have a sudden strong feeling of fear or worry and be unable to think clearly or calmly or decide what to do.", example: "Don't panic! We'll soon get you out of there." },
  { word: "quit", type: "v", definition: "to leave your job, school, etc.", example: "He quit his job after an argument with a colleague." },
  { word: "raft", type: "n", definition: "a flat structure made of pieces of wood tied together and used as a boat or floating platform.", example: "What happened to Kevin and Yossi on the raft?" },
  { word: "rate", type: "n", definition: "percentage, proportion, standard.", example: "The survival rate in all air crashes is historically 95.7 percent." },
  { word: "relieved", type: "adj", definition: "feeling happy because something unpleasant has stopped or has not happened.", example: "I was relieved to hear that they'd arrived safely." },
  { word: "safety", type: "n", definition: "security.", example: "The debate so far has focused mainly on safety issues." },
  { word: "scream", type: "v", definition: "to make a loud high noise with your voice because you are hurt, frightened, excited etc.", example: "The baby had a bad stomachache, and screamed all night." },
  { word: "seat pocket", type: "n", definition: "a small piece of material like a small bag added to a seat to carry things in it.", example: "She told everyone to put drink glasses into the seat pockets ahead of them." },
  { word: "slow down", type: "v", definition: "to start doing things at a slower speed.", example: "The key to survival is to slow down and divide the challenges into small tasks." },
  { word: "still", type: "adj", definition: "not moving; calm and quiet.", example: "The kids found it hard to stay still." },
  { word: "stunned", type: "adj", definition: "very surprised and unable to move or react.", example: "I just sat there stunned, watching it all on television." },
  { word: "thrilled", type: "adj", definition: "very excited.", example: "She was thrilled at the idea of flying to Europe." },
  { word: "upset", type: "adj", definition: "unhappy when something bad happens.", example: "Kate was terribly upset when her dog disappeared." },
  { word: "whisper", type: "v", definition: "to speak very quietly so that other people cannot hear what you are saying.", example: "You don't have to whisper, no one can hear us." }
];